"""initial migration

Revision ID: f7a44144a9ca
Revises: 
Create Date: 2025-03-06 02:38:11.097827

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7a44144a9ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Cur_ID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Cur_Abbreviation', sa.String(), nullable=False),
    sa.Column('Cur_Scale', sa.Integer(), nullable=False),
    sa.Column('Cur_Name', sa.String(), nullable=False),
    sa.Column('Cur_OfficialRate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_status_currency', 'exchanges', ['created_at', 'status', 'to_currency'], unique=False)
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_index('idx_date_status_currency', table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_table('currencies')
    # ### end Alembic commands ###
