version: '3.9'
services:
   db:
      image: postgres:16
      container_name: converter_db
      env_file:
         - .env-non-dev
      ports: 
         -  5433:5432
  

   converter:
      build:
         context: .
      env_file:
         - .env-non-dev
      depends_on:
         - db 
      ports:
         - 7777:8000


